server:
 port: 9000
spring:
 application:
  name : mbrt-service
 devtools:
  add-properties: true
# Enabling H2 Console
 h2:
  console:
   enabled: true
   h2path: /h2-console
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: password
 jpa: 
  database-platform: org.hibernate.dialect.H2Dialect
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
  show-sql: true
 zipkin: 
  base-url: http://localhost:9411/

logging:
 level:
  org: 
   springframework: DEBUG
   com.capgemini.mbrt: DEBUG
#spring.aop.auto = false
#eureka:
 #client:
  #service-url:
   #defaultZone: http://localhost:8000/eureka
   #register-with-eureka: true
   #fetch-registry: true
 #instance:
  #instance-id : ${spring.application.name}:${random.int}
      
